#ifndef _METADBL_SQLDEFINE_HPP_
#define _METADBL_SQLDEFINE_HPP_

#include "MetaDbl/CoreInclude.hpp"

#include <cstdint>
#include <cstring>

#include <mysql.h>

DECL_NAMESPACE_METADBL_BEGIN

enum SqlType {

    SQLTYPE_NONE = 0,
    SQLTYPE_INT8,
    SQLTYPE_UINT8,
    SQLTYPE_INT16,
    SQLTYPE_UINT16,
    SQLTYPE_INT32,
    SQLTYPE_UINT32,
    SQLTYPE_INT64,
    SQLTYPE_UINT64,
    SQLTYPE_FLOAT,
    SQLTYPE_DOUBLE,
    SQLTYPE_TIMESTAMP,
    SQLTYPE_STRING,
    SQLTYPE_VARSTRING,
    SQLTYPE_BINARY,
    SQLTYPE_COUNT,
};

DECL_NAMESPACE_METADBL_END

#endif // _METADBL_SQLDEFINE_HPP_
